pokemontrades/porygon-bot

bot.js

Also reverted that other thing so that the bot doesn't PM itself.

Fixed repetitive messages

---

commands/usernote.js

Fixed an issue where usernotes couldn't be added on a deleted comment/post.

Fix usernote issue

---

README.md
bot.js
commands/README.md
commands/checkball.js
commands/checkfc.js
commands/example.js
commands/highfive.js
commands/index.js
commands/messages.js
commands/pet.js
commands/search.js
commands/setusertimezone.js
commands/usernote.js
services/db.js

* Converted remaining commands into modules
* Changed behavior for .msg to display the message in the channel the message was sent in
* Added support for user-set time zones (for displaying message sent times in the recipient's local time).
To set a timezone, use .settimezone followed by a numeric offset, e.g. .settimezone -5 or .settimezone -03:30

Adjustments to modularization, additional functionality for .msg

---

bot.js
config.default.js
package.json

See the default config file for examples of how to filter commands.
This PR also cleans up a bit of code in bot.js.

Add command filtering by channel

---

bot.js
commands/README.md
commands/voiced.js

```
20:10:43 +Pelipper-Bot was voiced (+v) by @not_an_aardvark
20:10:43 <+Pelipper-Bot> n_n
20:10:48 Pelipper-Bot was de-voiced (-v) by @not_an_aardvark
20:10:48 <Pelipper-Bot> é_é
```

Added trigger for mode changes

---

bot.js
commands/checkfc.js
config.default.js
package.json
services/constants.js
tasks/README.md
tasks/example.js
tasks/index.js
tasks/reports.js

See [the readme](https://github.com/pokemontrades/porygon-bot/blob/71c6a6b639012f207f660bde9e051c72fbfaecd6/tasks/README.md) for details. The tasks are specified in the config file on a per-channel basis in the same format that commands are specified.

Add task API and report dumper

---

commands/snapshot.js

Kirzi requested.
I haven't tested it, because meh...

Add .snapshot command

---

commands/messages.js

Because I've been using ".tell", it feels a bit weird to type ".tell Someone is this a question?" for example. So it's purely me being weird, I'd like to be able to "ask" a question.

Add ask alias to message

---

commands/messages.js

Reverts pokemontrades/porygon-bot#37

Revert "Add ask alias to message"

---

commands/receiveMessage.js

Add PM notifications for messages in another channel

---

commands/usernote.js
config.default.js
services/usernote-helper.js
tasks/spam.js

This requires generating a new OAuth token (see config.default.js for details.)

Automate spam removal

---

commands/search.js

Disallow use of search command through PM

---

commands/usernote.js
config.default.js
services/usernote-helper.js

Added a config file for the usernote module, to be used for storing channel-specific permissions on which subreddits' usernotes can be accessed. It also contains a defaultSubreddit variable, used to replace a couple hardcoded references to pokemontrades.

Added channel-based usernote permissions

---

services/usernote-helper.js

This allows the bot to execute other commands while waiting for the usernote page to parse.

Use async versions of zlib.inflate and zlib.deflate

---

commands/fhq.js

Add .fhq command

---

commands/ss.js
package.json

Added a .ss command for retrieving the underlying Google Doc links for the new spreadsheet template. This mitigates the problem of having to click each individual Pokémon to see all the data.

Added .ss command for converting spreadsheet links

---

commands/usernote.js

Add tags as an alias to tag/usernote

---

commands/highfive.js

Make highfive properly case insensitive

---

bot.js
commands/README.md
commands/index.js
commands/usernote.js
config.default.js
services/db.js
services/reddit.js
services/usernote-helper.js
tasks/index.js
tasks/reports.js
tasks/spam.js

Allows you to disable any one of the outward connections, while also simplifying some of the config names and making it much easier to read and figure out what is happening.
I have tested this, but if someone else could test (preferably with the prod config) that would be great. I think I've caught all the changes.

Update config to have better sections

---

README.md
bot.js
commands/receiveMessage.js
commands/sendMessage.js
commands/setusertimezone.js
package.json
services/db/index.js
services/db/models/Alias.js
services/db/models/Message.js
services/db/models/User.js
services/db/models/index.js

This will allow us to plug in sqlite in the next PR.
This should obviously require full testing again.

Move from promise-mysql to squelize
